name: Continuous Integration App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Setup:
    uses: ./.github/workflows/setup-node.yml

  Test:
    needs: Setup
    uses: ./.github/workflows/test-code.yml

  Analyze:
    needs: Setup
    uses: ./.github/workflows/analyze-code.yml

  Build:
    needs: [Setup, Analyze]
    uses: ./.github/workflows/build-code.yml
