name: Reusable Workflow Test Code

on:
  workflow_call:

jobs:
  test:
    name: "[Test Code]"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "[Restore node modules]"
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-nodemodules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-nodemodules-

      - name: "[Run test]"
        run: yarn test
